In [1]:
import numpy as np

# Create the ndarray
a = np.arange(20)
print(type(a), " : ", a)

<class 'numpy.ndarray'>  :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [2]:
# method: Reshape the ndarray
a = a.reshape(2, 2, 5)
print(type(a), " : \n", a)

<class 'numpy.ndarray'>  : 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [3]:
# member: ndim shape size and dtype
print("a.ndim: ", a.ndim)
print("a.shape: ", a.shape)
print("a.size: ", a.size)
print("a.dtype: ", a.dtype)

a.ndim:  3
a.shape:  (2, 2, 5)
a.size:  20
a.dtype:  int32


In [4]:
# Create the array
raw = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
a = np.array(raw)
print(type(a), " : \n", a)

<class 'numpy.ndarray'>  : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
# Specified dim zeros
d = (4, 5)
print(type(d), "\n", np.zeros(d))

<class 'tuple'> 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
# Specified dim rand
np.random.rand(5)


array([0.09092864, 0.78701795, 0.82279413, 0.49577066, 0.87923136])